### ISSUE TITLE
Can not save configuration

### ISSUE THREAD

**Issue by E1iTeDa357** [DoctorMcKay/HSPI_WebHookNotifications#4] opened 2019-09-30 03:37 UTC
Log is filled with:
WebHook Notifications Debug | debug: Ignoring event VALUE_SET because no webhook endpoint is configured.
Entries...

Everytime I try to check a box or input in a url I get:
WebHook Notifications | warn: System.MissingMethodException: Method not found: System.Func`5   System.Net.Http.HttpClientHandler.get_DangerousAcceptAnyServerCertificateValidator()   at HSPI_WebHookNotifications.HSPI.PostBackProc (System.String  pageName, System.String data, System.String user, System.Int32  userRights) [0x000f3] in <50c2843d36d04fe5b8981e50b22445c9>

**Comment by DoctorMcKay** [comment] 2019-10-01 10:57
This sounds like a duplicate of #3.

**Closed as completed by DoctorMcKay** 2019-10-01 10:57 UTC
Labels: duplicate
